project_id = "thmhwdwqbroimrrfalkt"

[functions.crawl-news]
verify_jwt = false

[functions.analyze-news]
verify_jwt = false

[functions.generate-custom-insight]
verify_jwt = false

[functions.analyze-market-data]
verify_jwt = false

[functions.search-news]
verify_jwt = false

[functions.trend-briefing]
verify_jwt = false

[functions.analyze-dashboard]
verify_jwt = false
